//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_CustomerGroups
    {
        public string CustomerGroupID { get; set; }
        public string CustomerGroupName { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
