//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PMSSGP_200911Entities : DbContext
    {
        public PMSSGP_200911Entities()
            : base("name=PMSSGP_200911Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MM_Mailers> MM_Mailers { get; set; }
        public virtual DbSet<SGP_KT_THUHO> SGP_KT_THUHO { get; set; }
        public virtual DbSet<SGP_Email> SGP_Email { get; set; }
        public virtual DbSet<SGP_PackingList> SGP_PackingList { get; set; }
        public virtual DbSet<MM_CustomerGroups> MM_CustomerGroups { get; set; }
        public virtual DbSet<MM_Customers> MM_Customers { get; set; }
        public virtual DbSet<MM_MailerDeliveryDetail> MM_MailerDeliveryDetail { get; set; }
        public virtual DbSet<MM_PostOffices> MM_PostOffices { get; set; }
        public virtual DbSet<MM_Zones> MM_Zones { get; set; }
    
        public virtual ObjectResult<SGP_insertPackingList_Result> SGP_insertPackingList(string documentID)
        {
            var documentIDParameter = documentID != null ?
                new ObjectParameter("DocumentID", documentID) :
                new ObjectParameter("DocumentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_insertPackingList_Result>("SGP_insertPackingList", documentIDParameter);
        }
    
        public virtual ObjectResult<string> MM_CustomerGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MM_CustomerGroup");
        }
    
        public virtual ObjectResult<string> MM_FindCustomerID(string customerGroupID)
        {
            var customerGroupIDParameter = customerGroupID != null ?
                new ObjectParameter("CustomerGroupID", customerGroupID) :
                new ObjectParameter("CustomerGroupID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MM_FindCustomerID", customerGroupIDParameter);
        }
    }
}
