//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGP_PackingList
    {
        public string DocumentID { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string PostOfficeIDAccept { get; set; }
        public Nullable<int> NumberOfPackage { get; set; }
        public Nullable<double> Weight { get; set; }
        public string TripNumber { get; set; }
        public string Description { get; set; }
        public string DocumentOrder { get; set; }
        public string Tranport { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> RecieveDate { get; set; }
        public string RecieveDescription { get; set; }
    }
}
