//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGP_Email
    {
        public string PostOfficeID { get; set; }
        public string Email { get; set; }
        public string CC { get; set; }
    }
}
