//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGP_KT_THUHO
    {
        public string MailerID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DocID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Invoice { get; set; }
        public string Description { get; set; }
        public string UserID { get; set; }
    }
}
