//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.SGPLogin {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGPLogin.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPackingList(string postofficeidaccept, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPackingListAsync(string postofficeidaccept, string fromdate, string todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingListDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPackingListDetail(string documentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingListDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPackingListDetailAsync(string documentid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEmployees(string postofficeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeesAsync(string postofficeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePackingList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePackingList(int PackingListStatus, string AcceptDescription, string AcceptDate, string EmployeeAccept, string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePackingList", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePackingListAsync(int PackingListStatus, string AcceptDescription, string AcceptDate, string EmployeeAccept, string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePackingListDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePackingListDetail(string DocumentID, string MailerID, bool Accept, string AcceptNotes, string AcceptDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePackingListDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePackingListDetailAsync(string DocumentID, string MailerID, bool Accept, string AcceptNotes, string AcceptDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAcceptPackingListDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAcceptPackingListDetail(string DocumentID, string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAcceptPackingListDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAcceptPackingListDetailAsync(string DocumentID, string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserLogin(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserLoginAsync(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPostOfice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserPostOfice(string UserID, string PostOffice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserPostOfice", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetUserPostOficeAsync(string UserID, string PostOffice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaxDocumentID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMaxDocumentID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMaxDocumentID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMaxDocumentIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCODDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertCODDetails(string ID, string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCODDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertCODDetailsAsync(string ID, string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCOD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertCOD(string DocumentID, string DocumentDate, string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCOD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertCODAsync(string DocumentID, string DocumentDate, string Description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCOD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCOD(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCOD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCODAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCODDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCODDetails(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCODDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCODDetailsAsync(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCODDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateCODDetails(string ID, string DeliveryDate, string DeliveryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCODDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateCODDetailsAsync(string ID, string DeliveryDate, string DeliveryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingList1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPackingList1(string PostOfficeID, string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingList1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPackingList1Async(string PostOfficeID, string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCOD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteCOD(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCOD", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DeleteCODAsync(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingListDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPackingListDetails(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPackingListDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPackingListDetailsAsync(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerID(string MailerID, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerIDAsync(string MailerID, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPackingListDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertPackingListDetails(string DocumentID, string MailerID, string SendNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPackingListDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertPackingListDetailsAsync(string DocumentID, string MailerID, string SendNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePackingListAcceptDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdatePackingListAcceptDetails(string CurrentPostOfficeID, string CurrentStatusID, string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePackingListAcceptDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdatePackingListAcceptDetailsAsync(string CurrentPostOfficeID, string CurrentStatusID, string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertHistory(string MailerID, string PostOfficeID, string DocumentID, string UserGroupID, int Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertHistoryAsync(string MailerID, string PostOfficeID, string DocumentID, string UserGroupID, int Status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDelivery(string PostOfficeID, string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryAsync(string PostOfficeID, string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDeliveryDetails(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDetailsAsync(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDetailbyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDeliveryDetailbyID(string MailerID, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDetailbyID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDetailbyIDAsync(string MailerID, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMailerDeliveryDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertMailerDeliveryDetail(string DocumentID, string MailerID, string Notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMailerDeliveryDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertMailerDeliveryDetailAsync(string DocumentID, string MailerID, string Notes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMailerDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateMailerDelivery(string DocumentID, int MailerCount, int Quantity, double Weight, string UserGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMailerDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateMailerDeliveryAsync(string DocumentID, int MailerCount, int Quantity, double Weight, string UserGroupID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerCustomer(string FromDate, string ToDate, string PostOfficeID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerCustomerAsync(string FromDate, string ToDate, string PostOfficeID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGPGetDHL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGPGetDHL(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGPGetDHL", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGPGetDHLAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGPGetDHLByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGPGetDHLByID(string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGPGetDHLByID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGPGetDHLByIDAsync(string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryHNI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDeliveryHNI(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryHNI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryHNIAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryHNIBC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDeliveryHNIBC(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryHNIBC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryHNIBCAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKTVCKV1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetKTVCKV1(string FromDate, string ToDate, string BCGui, string BCNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKTVCKV1", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetKTVCKV1Async(string FromDate, string ToDate, string BCGui, string BCNhan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_01_SERVICEBYACCEPT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_SPT_CNTT_01_SERVICEBYACCEPT(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_01_SERVICEBYACCEPT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_01_SERVICEBYACCEPTAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_01_SERVICEBYSALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_SPT_CNTT_01_SERVICEBYSALE(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_01_SERVICEBYSALE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_01_SERVICEBYSALEAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_02_DELIVERY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_SPT_CNTT_02_DELIVERY(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_02_DELIVERY", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_02_DELIVERYAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryApp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDeliveryApp(string FromDate, string ToDate, string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryApp", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryAppAsync(string FromDate, string ToDate, string EmployeeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_03_CUSTOMERBYACCEPT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_SPT_CNTT_03_CUSTOMERBYACCEPT(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_03_CUSTOMERBYACCEPT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_03_CUSTOMERBYACCEPTAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_03_CUSTOMERBYSALE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_SPT_CNTT_03_CUSTOMERBYSALE(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_SPT_CNTT_03_CUSTOMERBYSALE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_03_CUSTOMERBYSALEAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_IT_M_TBTH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_IT_M_TBTH(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_IT_M_TBTH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_IT_M_TBTHAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDNG", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDeliveryDNG(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDNG", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDNGAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDNG_KV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailerDeliveryDNG_KV(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMailerDeliveryDNG_KV", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDNG_KVAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKTVCKV12BC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetKTVCKV12BC(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetKTVCKV12BC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetKTVCKV12BCAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_GETKGOTBNH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_GETKGOTBNH(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_GETKGOTBNH", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_GETKGOTBNHAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucher", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_CustomerDebitVoucher(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucher", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherAsync(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucherBK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_CustomerDebitVoucherBK(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucherBK", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherBKAsync(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucherBKCT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_CustomerDebitVoucherBKCT(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucherBKCT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherBKCTAsync(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucherCT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_CustomerDebitVoucherCT(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CustomerDebitVoucherCT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherCTAsync(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_GetEMSDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_GetEMSDetail(string MailerID, string Post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_GetEMSDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_GetEMSDetailAsync(string MailerID, string Post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_DoanhThu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_DoanhThu(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_DoanhThu", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_DoanhThuAsync(string FromDate, string ToDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaoCaoThang", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BaoCaoThang(string FromDate, string ToDate, string Post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BaoCaoThang", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BaoCaoThangAsync(string FromDate, string ToDate, string Post);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_InsertPackingListDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_PDA_InsertPackingListDetails(string UserGroupID, string PostOfficeID, string DocumentID, string[] ListCG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_InsertPackingListDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_InsertPackingListDetailsAsync(string UserGroupID, string PostOfficeID, string DocumentID, string[] ListCG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_GetPackingListID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_PDA_GetPackingListID(string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_GetPackingListID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_GetPackingListIDAsync(string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SGP_PDA_Login(string UserID, string Password, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_Login", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SGP_PDA_LoginAsync(string UserID, string Password, string PostOfficeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_UpdatePackingListDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_PDA_UpdatePackingListDetails(string EmployeeAccept, string PostOfficeIDAccept, string AcceptNotes, string UserGroupID, string[] ListCG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_UpdatePackingListDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_UpdatePackingListDetailsAsync(string EmployeeAccept, string PostOfficeIDAccept, string AcceptNotes, string UserGroupID, string[] ListCG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_GetEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_PDA_GetEmployee(string postofficeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_PDA_GetEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_GetEmployeeAsync(string postofficeid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_GetReturnInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SGP_GetReturnInfo(string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_GetReturnInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SGP_GetReturnInfoAsync(string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDHLPlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertDHLPlan(string ID, string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDHLPlan", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InsertDHLPlanAsync(string ID, string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_MailerDeliveryInsert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SGP_MailerDeliveryInsert(string DocumentID, string PostOfficeID, string EmployeeID, string Description, int NumberOfPackage, string UserGroupID, double MailerCount, double Quantity, double Weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_MailerDeliveryInsert", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SGP_MailerDeliveryInsertAsync(string DocumentID, string PostOfficeID, string EmployeeID, string Description, int NumberOfPackage, string UserGroupID, double MailerCount, double Quantity, double Weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_MaxMailerDeliveryDocumentID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SGP_MaxMailerDeliveryDocumentID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_MaxMailerDeliveryDocumentID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SGP_MaxMailerDeliveryDocumentIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_DeleteMailerDeliveryDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SGP_DeleteMailerDeliveryDetail(string DocumentID, string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_DeleteMailerDeliveryDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SGP_DeleteMailerDeliveryDetailAsync(string DocumentID, string MailerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CheckMailerDeliveryDocumentID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SGP_CheckMailerDeliveryDocumentID(string DocumentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SGP_CheckMailerDeliveryDocumentID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SGP_CheckMailerDeliveryDocumentIDAsync(string DocumentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : SGP.SGPLogin.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<SGP.SGPLogin.Service1Soap>, SGP.SGPLogin.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPackingList(string postofficeidaccept, string fromdate, string todate) {
            return base.Channel.GetPackingList(postofficeidaccept, fromdate, todate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPackingListAsync(string postofficeidaccept, string fromdate, string todate) {
            return base.Channel.GetPackingListAsync(postofficeidaccept, fromdate, todate);
        }
        
        public System.Data.DataSet GetPackingListDetail(string documentid) {
            return base.Channel.GetPackingListDetail(documentid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPackingListDetailAsync(string documentid) {
            return base.Channel.GetPackingListDetailAsync(documentid);
        }
        
        public System.Data.DataSet GetEmployees(string postofficeid) {
            return base.Channel.GetEmployees(postofficeid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmployeesAsync(string postofficeid) {
            return base.Channel.GetEmployeesAsync(postofficeid);
        }
        
        public string UpdatePackingList(int PackingListStatus, string AcceptDescription, string AcceptDate, string EmployeeAccept, string DocumentID) {
            return base.Channel.UpdatePackingList(PackingListStatus, AcceptDescription, AcceptDate, EmployeeAccept, DocumentID);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePackingListAsync(int PackingListStatus, string AcceptDescription, string AcceptDate, string EmployeeAccept, string DocumentID) {
            return base.Channel.UpdatePackingListAsync(PackingListStatus, AcceptDescription, AcceptDate, EmployeeAccept, DocumentID);
        }
        
        public string UpdatePackingListDetail(string DocumentID, string MailerID, bool Accept, string AcceptNotes, string AcceptDate) {
            return base.Channel.UpdatePackingListDetail(DocumentID, MailerID, Accept, AcceptNotes, AcceptDate);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePackingListDetailAsync(string DocumentID, string MailerID, bool Accept, string AcceptNotes, string AcceptDate) {
            return base.Channel.UpdatePackingListDetailAsync(DocumentID, MailerID, Accept, AcceptNotes, AcceptDate);
        }
        
        public System.Data.DataSet GetAcceptPackingListDetail(string DocumentID, string MailerID) {
            return base.Channel.GetAcceptPackingListDetail(DocumentID, MailerID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAcceptPackingListDetailAsync(string DocumentID, string MailerID) {
            return base.Channel.GetAcceptPackingListDetailAsync(DocumentID, MailerID);
        }
        
        public System.Data.DataSet GetUserLogin(string UserID) {
            return base.Channel.GetUserLogin(UserID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserLoginAsync(string UserID) {
            return base.Channel.GetUserLoginAsync(UserID);
        }
        
        public System.Data.DataSet GetUserPostOfice(string UserID, string PostOffice) {
            return base.Channel.GetUserPostOfice(UserID, PostOffice);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetUserPostOficeAsync(string UserID, string PostOffice) {
            return base.Channel.GetUserPostOficeAsync(UserID, PostOffice);
        }
        
        public System.Data.DataSet GetMaxDocumentID() {
            return base.Channel.GetMaxDocumentID();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMaxDocumentIDAsync() {
            return base.Channel.GetMaxDocumentIDAsync();
        }
        
        public string InsertCODDetails(string ID, string DocumentID) {
            return base.Channel.InsertCODDetails(ID, DocumentID);
        }
        
        public System.Threading.Tasks.Task<string> InsertCODDetailsAsync(string ID, string DocumentID) {
            return base.Channel.InsertCODDetailsAsync(ID, DocumentID);
        }
        
        public string InsertCOD(string DocumentID, string DocumentDate, string Description) {
            return base.Channel.InsertCOD(DocumentID, DocumentDate, Description);
        }
        
        public System.Threading.Tasks.Task<string> InsertCODAsync(string DocumentID, string DocumentDate, string Description) {
            return base.Channel.InsertCODAsync(DocumentID, DocumentDate, Description);
        }
        
        public System.Data.DataSet GetCOD(string FromDate, string ToDate) {
            return base.Channel.GetCOD(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCODAsync(string FromDate, string ToDate) {
            return base.Channel.GetCODAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet GetCODDetails(string DocumentID) {
            return base.Channel.GetCODDetails(DocumentID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCODDetailsAsync(string DocumentID) {
            return base.Channel.GetCODDetailsAsync(DocumentID);
        }
        
        public string UpdateCODDetails(string ID, string DeliveryDate, string DeliveryName) {
            return base.Channel.UpdateCODDetails(ID, DeliveryDate, DeliveryName);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCODDetailsAsync(string ID, string DeliveryDate, string DeliveryName) {
            return base.Channel.UpdateCODDetailsAsync(ID, DeliveryDate, DeliveryName);
        }
        
        public System.Data.DataSet GetPackingList1(string PostOfficeID, string FromDate, string ToDate) {
            return base.Channel.GetPackingList1(PostOfficeID, FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPackingList1Async(string PostOfficeID, string FromDate, string ToDate) {
            return base.Channel.GetPackingList1Async(PostOfficeID, FromDate, ToDate);
        }
        
        public string DeleteCOD(string DocumentID) {
            return base.Channel.DeleteCOD(DocumentID);
        }
        
        public System.Threading.Tasks.Task<string> DeleteCODAsync(string DocumentID) {
            return base.Channel.DeleteCODAsync(DocumentID);
        }
        
        public System.Data.DataSet GetPackingListDetails(string DocumentID) {
            return base.Channel.GetPackingListDetails(DocumentID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPackingListDetailsAsync(string DocumentID) {
            return base.Channel.GetPackingListDetailsAsync(DocumentID);
        }
        
        public System.Data.DataSet GetMailerID(string MailerID, string PostOfficeID) {
            return base.Channel.GetMailerID(MailerID, PostOfficeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerIDAsync(string MailerID, string PostOfficeID) {
            return base.Channel.GetMailerIDAsync(MailerID, PostOfficeID);
        }
        
        public string InsertPackingListDetails(string DocumentID, string MailerID, string SendNotes) {
            return base.Channel.InsertPackingListDetails(DocumentID, MailerID, SendNotes);
        }
        
        public System.Threading.Tasks.Task<string> InsertPackingListDetailsAsync(string DocumentID, string MailerID, string SendNotes) {
            return base.Channel.InsertPackingListDetailsAsync(DocumentID, MailerID, SendNotes);
        }
        
        public string UpdatePackingListAcceptDetails(string CurrentPostOfficeID, string CurrentStatusID, string MailerID) {
            return base.Channel.UpdatePackingListAcceptDetails(CurrentPostOfficeID, CurrentStatusID, MailerID);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePackingListAcceptDetailsAsync(string CurrentPostOfficeID, string CurrentStatusID, string MailerID) {
            return base.Channel.UpdatePackingListAcceptDetailsAsync(CurrentPostOfficeID, CurrentStatusID, MailerID);
        }
        
        public string InsertHistory(string MailerID, string PostOfficeID, string DocumentID, string UserGroupID, int Status) {
            return base.Channel.InsertHistory(MailerID, PostOfficeID, DocumentID, UserGroupID, Status);
        }
        
        public System.Threading.Tasks.Task<string> InsertHistoryAsync(string MailerID, string PostOfficeID, string DocumentID, string UserGroupID, int Status) {
            return base.Channel.InsertHistoryAsync(MailerID, PostOfficeID, DocumentID, UserGroupID, Status);
        }
        
        public System.Data.DataSet GetMailerDelivery(string PostOfficeID, string FromDate, string ToDate) {
            return base.Channel.GetMailerDelivery(PostOfficeID, FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryAsync(string PostOfficeID, string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryAsync(PostOfficeID, FromDate, ToDate);
        }
        
        public System.Data.DataSet GetMailerDeliveryDetails(string DocumentID) {
            return base.Channel.GetMailerDeliveryDetails(DocumentID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDetailsAsync(string DocumentID) {
            return base.Channel.GetMailerDeliveryDetailsAsync(DocumentID);
        }
        
        public System.Data.DataSet GetMailerDeliveryDetailbyID(string MailerID, string PostOfficeID) {
            return base.Channel.GetMailerDeliveryDetailbyID(MailerID, PostOfficeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDetailbyIDAsync(string MailerID, string PostOfficeID) {
            return base.Channel.GetMailerDeliveryDetailbyIDAsync(MailerID, PostOfficeID);
        }
        
        public string InsertMailerDeliveryDetail(string DocumentID, string MailerID, string Notes) {
            return base.Channel.InsertMailerDeliveryDetail(DocumentID, MailerID, Notes);
        }
        
        public System.Threading.Tasks.Task<string> InsertMailerDeliveryDetailAsync(string DocumentID, string MailerID, string Notes) {
            return base.Channel.InsertMailerDeliveryDetailAsync(DocumentID, MailerID, Notes);
        }
        
        public string UpdateMailerDelivery(string DocumentID, int MailerCount, int Quantity, double Weight, string UserGroupID) {
            return base.Channel.UpdateMailerDelivery(DocumentID, MailerCount, Quantity, Weight, UserGroupID);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMailerDeliveryAsync(string DocumentID, int MailerCount, int Quantity, double Weight, string UserGroupID) {
            return base.Channel.UpdateMailerDeliveryAsync(DocumentID, MailerCount, Quantity, Weight, UserGroupID);
        }
        
        public System.Data.DataSet GetMailerCustomer(string FromDate, string ToDate, string PostOfficeID, string CustomerID) {
            return base.Channel.GetMailerCustomer(FromDate, ToDate, PostOfficeID, CustomerID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerCustomerAsync(string FromDate, string ToDate, string PostOfficeID, string CustomerID) {
            return base.Channel.GetMailerCustomerAsync(FromDate, ToDate, PostOfficeID, CustomerID);
        }
        
        public System.Data.DataSet SGPGetDHL(string FromDate, string ToDate) {
            return base.Channel.SGPGetDHL(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGPGetDHLAsync(string FromDate, string ToDate) {
            return base.Channel.SGPGetDHLAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet SGPGetDHLByID(string MailerID) {
            return base.Channel.SGPGetDHLByID(MailerID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGPGetDHLByIDAsync(string MailerID) {
            return base.Channel.SGPGetDHLByIDAsync(MailerID);
        }
        
        public System.Data.DataSet GetMailerDeliveryHNI(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryHNI(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryHNIAsync(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryHNIAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet GetMailerDeliveryHNIBC(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryHNIBC(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryHNIBCAsync(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryHNIBCAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet GetKTVCKV1(string FromDate, string ToDate, string BCGui, string BCNhan) {
            return base.Channel.GetKTVCKV1(FromDate, ToDate, BCGui, BCNhan);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetKTVCKV1Async(string FromDate, string ToDate, string BCGui, string BCNhan) {
            return base.Channel.GetKTVCKV1Async(FromDate, ToDate, BCGui, BCNhan);
        }
        
        public System.Data.DataSet SGP_SPT_CNTT_01_SERVICEBYACCEPT(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_01_SERVICEBYACCEPT(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_01_SERVICEBYACCEPTAsync(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_01_SERVICEBYACCEPTAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet SGP_SPT_CNTT_01_SERVICEBYSALE(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_01_SERVICEBYSALE(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_01_SERVICEBYSALEAsync(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_01_SERVICEBYSALEAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet SGP_SPT_CNTT_02_DELIVERY(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_02_DELIVERY(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_02_DELIVERYAsync(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_02_DELIVERYAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet GetMailerDeliveryApp(string FromDate, string ToDate, string EmployeeID) {
            return base.Channel.GetMailerDeliveryApp(FromDate, ToDate, EmployeeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryAppAsync(string FromDate, string ToDate, string EmployeeID) {
            return base.Channel.GetMailerDeliveryAppAsync(FromDate, ToDate, EmployeeID);
        }
        
        public System.Data.DataSet SGP_SPT_CNTT_03_CUSTOMERBYACCEPT(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_03_CUSTOMERBYACCEPT(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_03_CUSTOMERBYACCEPTAsync(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_03_CUSTOMERBYACCEPTAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet SGP_SPT_CNTT_03_CUSTOMERBYSALE(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_03_CUSTOMERBYSALE(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_SPT_CNTT_03_CUSTOMERBYSALEAsync(string FromDate, string ToDate) {
            return base.Channel.SGP_SPT_CNTT_03_CUSTOMERBYSALEAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet Get_IT_M_TBTH(string FromDate, string ToDate) {
            return base.Channel.Get_IT_M_TBTH(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_IT_M_TBTHAsync(string FromDate, string ToDate) {
            return base.Channel.Get_IT_M_TBTHAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet GetMailerDeliveryDNG(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryDNG(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDNGAsync(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryDNGAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet GetMailerDeliveryDNG_KV(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryDNG_KV(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailerDeliveryDNG_KVAsync(string FromDate, string ToDate) {
            return base.Channel.GetMailerDeliveryDNG_KVAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet GetKTVCKV12BC(string FromDate, string ToDate) {
            return base.Channel.GetKTVCKV12BC(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetKTVCKV12BCAsync(string FromDate, string ToDate) {
            return base.Channel.GetKTVCKV12BCAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet SGP_GETKGOTBNH(string FromDate, string ToDate) {
            return base.Channel.SGP_GETKGOTBNH(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_GETKGOTBNHAsync(string FromDate, string ToDate) {
            return base.Channel.SGP_GETKGOTBNHAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet SGP_CustomerDebitVoucher(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type) {
            return base.Channel.SGP_CustomerDebitVoucher(FromDate, ToDate, PostOffice, FromMonth, ToMonth, FromYear, ToYear, Type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherAsync(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type) {
            return base.Channel.SGP_CustomerDebitVoucherAsync(FromDate, ToDate, PostOffice, FromMonth, ToMonth, FromYear, ToYear, Type);
        }
        
        public System.Data.DataSet SGP_CustomerDebitVoucherBK(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type) {
            return base.Channel.SGP_CustomerDebitVoucherBK(FromDate, ToDate, PostOffice, FromMonth, ToMonth, FromYear, ToYear, Type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherBKAsync(string FromDate, string ToDate, string PostOffice, int FromMonth, int ToMonth, int FromYear, int ToYear, int Type) {
            return base.Channel.SGP_CustomerDebitVoucherBKAsync(FromDate, ToDate, PostOffice, FromMonth, ToMonth, FromYear, ToYear, Type);
        }
        
        public System.Data.DataSet SGP_CustomerDebitVoucherBKCT(string DocumentID) {
            return base.Channel.SGP_CustomerDebitVoucherBKCT(DocumentID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherBKCTAsync(string DocumentID) {
            return base.Channel.SGP_CustomerDebitVoucherBKCTAsync(DocumentID);
        }
        
        public System.Data.DataSet SGP_CustomerDebitVoucherCT(string DocumentID) {
            return base.Channel.SGP_CustomerDebitVoucherCT(DocumentID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_CustomerDebitVoucherCTAsync(string DocumentID) {
            return base.Channel.SGP_CustomerDebitVoucherCTAsync(DocumentID);
        }
        
        public System.Data.DataSet SGP_GetEMSDetail(string MailerID, string Post) {
            return base.Channel.SGP_GetEMSDetail(MailerID, Post);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_GetEMSDetailAsync(string MailerID, string Post) {
            return base.Channel.SGP_GetEMSDetailAsync(MailerID, Post);
        }
        
        public System.Data.DataSet SGP_DoanhThu(string FromDate, string ToDate) {
            return base.Channel.SGP_DoanhThu(FromDate, ToDate);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_DoanhThuAsync(string FromDate, string ToDate) {
            return base.Channel.SGP_DoanhThuAsync(FromDate, ToDate);
        }
        
        public System.Data.DataSet BaoCaoThang(string FromDate, string ToDate, string Post) {
            return base.Channel.BaoCaoThang(FromDate, ToDate, Post);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BaoCaoThangAsync(string FromDate, string ToDate, string Post) {
            return base.Channel.BaoCaoThangAsync(FromDate, ToDate, Post);
        }
        
        public System.Data.DataSet SGP_PDA_InsertPackingListDetails(string UserGroupID, string PostOfficeID, string DocumentID, string[] ListCG) {
            return base.Channel.SGP_PDA_InsertPackingListDetails(UserGroupID, PostOfficeID, DocumentID, ListCG);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_InsertPackingListDetailsAsync(string UserGroupID, string PostOfficeID, string DocumentID, string[] ListCG) {
            return base.Channel.SGP_PDA_InsertPackingListDetailsAsync(UserGroupID, PostOfficeID, DocumentID, ListCG);
        }
        
        public System.Data.DataSet SGP_PDA_GetPackingListID(string PostOfficeID) {
            return base.Channel.SGP_PDA_GetPackingListID(PostOfficeID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_GetPackingListIDAsync(string PostOfficeID) {
            return base.Channel.SGP_PDA_GetPackingListIDAsync(PostOfficeID);
        }
        
        public int SGP_PDA_Login(string UserID, string Password, string PostOfficeID) {
            return base.Channel.SGP_PDA_Login(UserID, Password, PostOfficeID);
        }
        
        public System.Threading.Tasks.Task<int> SGP_PDA_LoginAsync(string UserID, string Password, string PostOfficeID) {
            return base.Channel.SGP_PDA_LoginAsync(UserID, Password, PostOfficeID);
        }
        
        public System.Data.DataSet SGP_PDA_UpdatePackingListDetails(string EmployeeAccept, string PostOfficeIDAccept, string AcceptNotes, string UserGroupID, string[] ListCG) {
            return base.Channel.SGP_PDA_UpdatePackingListDetails(EmployeeAccept, PostOfficeIDAccept, AcceptNotes, UserGroupID, ListCG);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_UpdatePackingListDetailsAsync(string EmployeeAccept, string PostOfficeIDAccept, string AcceptNotes, string UserGroupID, string[] ListCG) {
            return base.Channel.SGP_PDA_UpdatePackingListDetailsAsync(EmployeeAccept, PostOfficeIDAccept, AcceptNotes, UserGroupID, ListCG);
        }
        
        public System.Data.DataSet SGP_PDA_GetEmployee(string postofficeid) {
            return base.Channel.SGP_PDA_GetEmployee(postofficeid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_PDA_GetEmployeeAsync(string postofficeid) {
            return base.Channel.SGP_PDA_GetEmployeeAsync(postofficeid);
        }
        
        public System.Data.DataSet SGP_GetReturnInfo(string MailerID) {
            return base.Channel.SGP_GetReturnInfo(MailerID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SGP_GetReturnInfoAsync(string MailerID) {
            return base.Channel.SGP_GetReturnInfoAsync(MailerID);
        }
        
        public string InsertDHLPlan(string ID, string DocumentID) {
            return base.Channel.InsertDHLPlan(ID, DocumentID);
        }
        
        public System.Threading.Tasks.Task<string> InsertDHLPlanAsync(string ID, string DocumentID) {
            return base.Channel.InsertDHLPlanAsync(ID, DocumentID);
        }
        
        public string SGP_MailerDeliveryInsert(string DocumentID, string PostOfficeID, string EmployeeID, string Description, int NumberOfPackage, string UserGroupID, double MailerCount, double Quantity, double Weight) {
            return base.Channel.SGP_MailerDeliveryInsert(DocumentID, PostOfficeID, EmployeeID, Description, NumberOfPackage, UserGroupID, MailerCount, Quantity, Weight);
        }
        
        public System.Threading.Tasks.Task<string> SGP_MailerDeliveryInsertAsync(string DocumentID, string PostOfficeID, string EmployeeID, string Description, int NumberOfPackage, string UserGroupID, double MailerCount, double Quantity, double Weight) {
            return base.Channel.SGP_MailerDeliveryInsertAsync(DocumentID, PostOfficeID, EmployeeID, Description, NumberOfPackage, UserGroupID, MailerCount, Quantity, Weight);
        }
        
        public string SGP_MaxMailerDeliveryDocumentID() {
            return base.Channel.SGP_MaxMailerDeliveryDocumentID();
        }
        
        public System.Threading.Tasks.Task<string> SGP_MaxMailerDeliveryDocumentIDAsync() {
            return base.Channel.SGP_MaxMailerDeliveryDocumentIDAsync();
        }
        
        public string SGP_DeleteMailerDeliveryDetail(string DocumentID, string MailerID) {
            return base.Channel.SGP_DeleteMailerDeliveryDetail(DocumentID, MailerID);
        }
        
        public System.Threading.Tasks.Task<string> SGP_DeleteMailerDeliveryDetailAsync(string DocumentID, string MailerID) {
            return base.Channel.SGP_DeleteMailerDeliveryDetailAsync(DocumentID, MailerID);
        }
        
        public string SGP_CheckMailerDeliveryDocumentID(string DocumentID) {
            return base.Channel.SGP_CheckMailerDeliveryDocumentID(DocumentID);
        }
        
        public System.Threading.Tasks.Task<string> SGP_CheckMailerDeliveryDocumentIDAsync(string DocumentID) {
            return base.Channel.SGP_CheckMailerDeliveryDocumentIDAsync(DocumentID);
        }
    }
}
