//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentResult", Namespace="http://schemas.datacontract.org/2004/07/SAIGONPOSTAPI.Models")]
    [System.SerializableAttribute()]
    public partial class DocumentResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Imailerscan")]
    public interface Imailerscan {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imailerscan/DocumentScan", ReplyAction="http://tempuri.org/Imailerscan/DocumentScanResponse")]
        SGP.ServiceReference1.DocumentResult[] DocumentScan(string[] documents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Imailerscan/DocumentScan", ReplyAction="http://tempuri.org/Imailerscan/DocumentScanResponse")]
        System.Threading.Tasks.Task<SGP.ServiceReference1.DocumentResult[]> DocumentScanAsync(string[] documents);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImailerscanChannel : SGP.ServiceReference1.Imailerscan, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImailerscanClient : System.ServiceModel.ClientBase<SGP.ServiceReference1.Imailerscan>, SGP.ServiceReference1.Imailerscan {
        
        public ImailerscanClient() {
        }
        
        public ImailerscanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImailerscanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImailerscanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImailerscanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SGP.ServiceReference1.DocumentResult[] DocumentScan(string[] documents) {
            return base.Channel.DocumentScan(documents);
        }
        
        public System.Threading.Tasks.Task<SGP.ServiceReference1.DocumentResult[]> DocumentScanAsync(string[] documents) {
            return base.Channel.DocumentScanAsync(documents);
        }
    }
}
