//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityInfo
    {
        public ActivityInfo()
        {
            this.Comments = new HashSet<Comment>();
            this.FileAttaches = new HashSet<FileAttach>();
            this.ZoneInfoes = new HashSet<ZoneInfo>();
        }
    
        public string Id { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UserPost { get; set; }
        public string PostOfficeId { get; set; }
        public Nullable<int> IsClock { get; set; }
        public string UserLock { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<FileAttach> FileAttaches { get; set; }
        public virtual ICollection<ZoneInfo> ZoneInfoes { get; set; }
        public virtual WK_PostOffice WK_PostOffice { get; set; }
    }
}
