//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault
    {
        public Fault()
        {
            this.ReportOnlines = new HashSet<ReportOnline>();
        }
    
        public int IDFault { get; set; }
        public string FaultName { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual ICollection<ReportOnline> ReportOnlines { get; set; }
    }
}
