//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileAttachComment
    {
        public string Id { get; set; }
        public string DocumentName { get; set; }
        public string DocumentPath { get; set; }
        public string DoucumentType { get; set; }
        public string CommentId { get; set; }
    
        public virtual Comment Comment { get; set; }
    }
}
