//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MM_MailerDelivery
    {
        public MM_MailerDelivery()
        {
            this.MM_MailerDeliveryDetail = new HashSet<MM_MailerDeliveryDetail>();
        }
    
        public string DocumentID { get; set; }
        public string TripNumber { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<System.DateTime> DocumentTime { get; set; }
        public string PostOfficeID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> MailerCount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string NumberOfPackage { get; set; }
        public string UserGroupID { get; set; }
        public Nullable<System.DateTime> LastUpdDate { get; set; }
        public int RecordState { get; set; }
        public bool SyncFlag { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
    
        public virtual MM_PostOffices MM_PostOffices { get; set; }
        public virtual ICollection<MM_MailerDeliveryDetail> MM_MailerDeliveryDetail { get; set; }
    }
}
