//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOnline
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string IDReceipt { get; set; }
        public string DetailContent { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IDFault { get; set; }
        public string Status { get; set; }
    
        public virtual Fault Fault { get; set; }
    }
}
