//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SGPAPIEntities : DbContext
    {
        public SGPAPIEntities()
            : base("name=SGPAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fault> Faults { get; set; }
        public virtual DbSet<ReportOnline> ReportOnlines { get; set; }
        public virtual DbSet<ActivityInfo> ActivityInfoes { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<FileAttach> FileAttaches { get; set; }
        public virtual DbSet<FileAttachComment> FileAttachComments { get; set; }
        public virtual DbSet<SGPWiki> SGPWikis { get; set; }
        public virtual DbSet<ZoneInfo> ZoneInfoes { get; set; }
        public virtual DbSet<WK_PostOffice> WK_PostOffice { get; set; }
        public virtual DbSet<UMS_tblUserAccount> UMS_tblUserAccount { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    
        public virtual ObjectResult<SGP_WEB_Mailer_Result> SGP_WEB_Mailer(string fromdate, string toDate)
        {
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_WEB_Mailer_Result>("SGP_WEB_Mailer", fromdateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SGP_WEB_AmountByMonth_Result> SGP_WEB_AmountByMonth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_WEB_AmountByMonth_Result>("SGP_WEB_AmountByMonth");
        }
    
        public virtual ObjectResult<SGP_WEB_ReportOnline_Result> SGP_WEB_ReportOnline()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_WEB_ReportOnline_Result>("SGP_WEB_ReportOnline");
        }
    
        public virtual ObjectResult<SGP_WEB_DuongTruc_BCKT_Result> SGP_WEB_DuongTruc_BCKT(string fromDate, string toDate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_WEB_DuongTruc_BCKT_Result>("SGP_WEB_DuongTruc_BCKT", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SGP_WEB_DuongTruc_KTNhan_Result> SGP_WEB_DuongTruc_KTNhan(string fromDate, string toDate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_WEB_DuongTruc_KTNhan_Result>("SGP_WEB_DuongTruc_KTNhan", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<SGP_WEB_MailerBySaleDate_Result> SGP_WEB_MailerBySaleDate(string fromDate, string toDate, string zoneID)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var zoneIDParameter = zoneID != null ?
                new ObjectParameter("ZoneID", zoneID) :
                new ObjectParameter("ZoneID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_WEB_MailerBySaleDate_Result>("SGP_WEB_MailerBySaleDate", fromDateParameter, toDateParameter, zoneIDParameter);
        }
    
        public virtual ObjectResult<SGP_WEB_MailerByDate_Result> SGP_WEB_MailerByDate(string fromDate, string toDate, string zoneID)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var zoneIDParameter = zoneID != null ?
                new ObjectParameter("ZoneID", zoneID) :
                new ObjectParameter("ZoneID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SGP_WEB_MailerByDate_Result>("SGP_WEB_MailerByDate", fromDateParameter, toDateParameter, zoneIDParameter);
        }
    }
}
