//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DHLPlan
    {
        public int ID { get; set; }
        public string D_O { get; set; }
        public Nullable<System.DateTime> PGI { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string ToZone { get; set; }
        public string ZoneDesc { get; set; }
        public string ToNodeCode { get; set; }
        public string ShiptoNM { get; set; }
        public string ShiptoAddress { get; set; }
        public Nullable<int> Quatity { get; set; }
        public string Unit1 { get; set; }
        public Nullable<int> Weight { get; set; }
        public string Unit2 { get; set; }
        public string Subcon { get; set; }
        public string CG { get; set; }
        public Nullable<int> SL { get; set; }
        public Nullable<int> TL { get; set; }
        public string TP { get; set; }
        public string KH { get; set; }
        public string Unit3 { get; set; }
        public string TongSL { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string Contact3 { get; set; }
        public string Employee { get; set; }
        public string Zone { get; set; }
    }
}
