//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test1Entities : DbContext
    {
        public Test1Entities()
            : base("name=Test1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MM_MailerDelivery> MM_MailerDelivery { get; set; }
        public virtual DbSet<MM_MailerDeliveryDetail> MM_MailerDeliveryDetail { get; set; }
        public virtual DbSet<MM_PostOffices> MM_PostOffices { get; set; }
        public virtual DbSet<ActivityInfo> ActivityInfoes { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<FileAttach> FileAttaches { get; set; }
        public virtual DbSet<FileAttachComment> FileAttachComments { get; set; }
        public virtual DbSet<SGPWiki> SGPWikis { get; set; }
        public virtual DbSet<ZoneInfo> ZoneInfoes { get; set; }
    }
}
