//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UMS_tblUserAccount
    {
        public string UserGroupID { get; set; }
        public string Password { get; set; }
        public string UserGroupName { get; set; }
        public bool FValid { get; set; }
        public bool FGroup { get; set; }
        public bool FAdm { get; set; }
        public bool FSpv { get; set; }
        public string Description { get; set; }
        public bool CantChangePwd { get; set; }
        public bool PwdNeverExpire { get; set; }
        public bool MustChangePwd { get; set; }
        public Nullable<System.DateTime> DateOfChangePwd { get; set; }
        public Nullable<System.DateTime> LastEditDate { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string MemberOf { get; set; }
    }
}
