//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WK_PostOffice
    {
        public WK_PostOffice()
        {
            this.ActivityInfoes = new HashSet<ActivityInfo>();
            this.Comments = new HashSet<Comment>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ZoneId { get; set; }
        public string ProvinceId { get; set; }
    
        public virtual ICollection<ActivityInfo> ActivityInfoes { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
