//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneInfo
    {
        public ZoneInfo()
        {
            this.ActivityInfoes = new HashSet<ActivityInfo>();
        }
    
        public string ZoneId { get; set; }
        public string ZoneName { get; set; }
    
        public virtual ICollection<ActivityInfo> ActivityInfoes { get; set; }
    }
}
